# Generated by Django 2.2 on 2020-07-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chpa_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='s_age',
            field=models.IntegerField(default=2),
        ),
    ]
