# Generated by Django 2.2 on 2020-07-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chpa_data', '0002_data_s_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='aaa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.IntegerField(default=1)),
                ('s_age', models.IntegerField(default=2)),
            ],
        ),
    ]
