# Generated by Django 2.2 on 2020-08-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chpa_data', '0003_aaa'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TCI', models.CharField(max_length=255)),
                ('TCII', models.CharField(max_length=255)),
                ('TCIII', models.CharField(max_length=255)),
                ('TCIV', models.CharField(max_length=255)),
                ('MOLECULE', models.CharField(max_length=255)),
                ('PRODUCT', models.CharField(max_length=255)),
                ('PACKAGE', models.CharField(max_length=255)),
                ('CORPORATION', models.CharField(max_length=255)),
                ('MANUF_TYPE', models.CharField(max_length=255)),
                ('FORMULATION', models.CharField(max_length=255)),
                ('STRENGTH', models.CharField(max_length=255)),
                ('AMOUNT', models.IntegerField(default=1)),
                ('UNIT', models.CharField(max_length=255)),
                ('PERIOD', models.CharField(max_length=255)),
                ('DATE', models.DateTimeField()),
            ],
        ),
    ]
